# Generated by Django 6.0 on 2026-01-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_datospersonales_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospersonales',
            name='usuario',
        ),
        migrations.CreateModel(
            name='ConfiguracionCV',
            fields=[
                ('idconfiguracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_configuracion', models.CharField(default='Mi CV Principal', max_length=100)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_ventas_garage', models.BooleanField(default=False)),
                ('estilo_visual', models.CharField(choices=[('minimalista', 'Minimalista'), ('moderno', 'Moderno'), ('clasico', 'Clásico'), ('creativo', 'Creativo')], default='minimalista', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=True)),
                ('idperfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_cv', to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Configuración CV',
                'verbose_name_plural': 'Configuraciones CV',
                'db_table': 'configuracioncv',
            },
        ),
    ]
