# Generated by Django 6.0 on 2026-01-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_remove_datospersonales_usuario_configuracioncv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosacademicos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='productos_academicos/'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ConfiguracionCV',
        ),
    ]
