# Generated by Django 6.0 on 2026-01-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_productosacademicos_archivo_productosacademicos_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoslaborales',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='productos_laborales/'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas_garage/'),
        ),
    ]
