# Generated by Django 6.0 on 2026-01-22 20:37

import curriculum.models
import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_datospersonales_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'ordering': ['-fechainicio']},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fechainiciogestion']},
        ),
        migrations.AlterModelOptions(
            name='productosacademicos',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterModelOptions(
            name='productoslaborales',
            options={'ordering': ['-fechaproducto']},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'ordering': ['-fechareconocimiento']},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RenameField(
            model_name='ventagarage',
            old_name='imagen',
            new_name='imagen_producto',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_cursos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_experiencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_academicos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_productos_laborales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_reconocimientos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_venta_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today, validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura, curriculum.models.validar_rango_edad_realista]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'La cédula debe contener exactamente 10 dígitos numéricos')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(choices=[('Ingeniería', 'Ingeniería'), ('Tecnología', 'Tecnología'), ('Docencia', 'Docencia'), ('Investigación', 'Investigación'), ('Otro', 'Otro')], default='Otro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(validators=[curriculum.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
