# Generated by Django 6.0 on 2026-01-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_cursosrealizados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_cursos',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Cursos?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_experiencia',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Experiencia?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_productos_academico',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Productos Académicos?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_productos_laborales',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Productos Laborales?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_reconocimientos',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Reconocimientos?'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='imprimir_venta_garage',
            field=models.BooleanField(default=True, verbose_name='¿Imprimir Venta Garage?'),
        ),
    ]
