# Generated by Django 6.0 on 2026-01-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_datospersonales_imprimir_cursos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='imprimir_productos_academico',
            new_name='imprimir_productos_academicos',
        ),
    ]
