# Generated by Django 6.0 on 2026-01-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosacademicos',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
